//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutImpl.java
//

#include "AbsoluteLayout.h"
#include "AbsoluteLayoutImpl.h"
#include "BaseHasWidgets.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSObjectArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "IdGenerator.h"
#include "J2ObjC_source.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"


#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl () {
 @public
  id uiView_;
  ADAbsoluteLayout *absoluteLayout_;
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *builder_;
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *bean_;
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *paramsBuilder_;
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *paramsBean_;
}

- (void)setWidgetOnNativeClass;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ADAbsoluteLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

@end

J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, absoluteLayout_, ADAbsoluteLayout *)
J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, builder_, ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)
J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, bean_, ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *)
J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, paramsBuilder_, ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)
J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, paramsBean_, ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *)

__attribute__((unused)) static void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_setWidgetOnNativeClass(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self);

__attribute__((unused)) static void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_createLayoutParamsWithADView_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, ADView *view);

__attribute__((unused)) static ADAbsoluteLayout_LayoutParams *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_getLayoutParamsWithADView_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, ADView *view);

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt () {
 @public
  __unsafe_unretained ComAsheraAbsolutelayoutAbsoluteLayoutImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  jint mMaxWidth_;
  jint mMaxHeight_;
}

@end

J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt, onLayoutEvent_, ASOnLayoutEvent *)

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder () {
 @public
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl *this$0_;
}

@end

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean () {
 @public
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl *this$0_;
}

@end

NSString *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_LOCAL_NAME = @"AbsoluteLayout";
NSString *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_GROUP_NAME = @"AbsoluteLayout";

@implementation ComAsheraAbsolutelayoutAbsoluteLayoutImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_x"])) withTypeWithNSString:@"dimension"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_y"])) withTypeWithNSString:@"dimension"])) forChild]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init();
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  absoluteLayout_ = new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return absoluteLayout_;
}

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w {
  jboolean remove = [super removeWithASIWidget:w];
  [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(w);
  return remove;
}

- (jboolean)removeWithInt:(jint)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  jboolean remove = [super removeWithInt:index];
  if (index + 1 <= [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) getChildCount]) {
    [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) removeViewAtWithInt:index];
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
  return remove;
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ComAsheraAbsolutelayoutAbsoluteLayoutImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) addViewWithADView:view];
    }
    else {
      [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_createLayoutParamsWithADView_(self, view);
}

- (ADAbsoluteLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ComAsheraAbsolutelayoutAbsoluteLayoutImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADAbsoluteLayout_LayoutParams *layoutParams = ComAsheraAbsolutelayoutAbsoluteLayoutImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_x", @"layout_y" }, 4)) {
    case 0:
    ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 2:
    {
      ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->x_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    }
    break;
    case 3:
    {
      ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->y_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    }
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADAbsoluteLayout_LayoutParams *layoutParams = ComAsheraAbsolutelayoutAbsoluteLayoutImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_x", @"layout_y" }, 4)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->height_);
    case 2:
    {
      return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->x_);
    }
    case 3:
    {
      return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->y_);
    }
  }
  return nil;
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *) nil_chk(((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *) cast_chk(absoluteLayout_, [ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt class])))) updateMeasuredDimensionWithInt:width withInt:height];
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) setIdWithInt:ASIdGenerator_getIdWithNSString_(id_)];
  }
}

- (id)getPluginWithNSString:(NSString *)plugin {
  return [((id<ASIAttributable>) nil_chk(ASWidgetFactory_getAttributableWithNSString_(plugin))) newInstanceWithASIWidget:self];
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *)getBean {
  if (bean_ == nil) {
    bean_ = new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self);
  }
  return bean_;
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)getBuilder {
  if (builder_ == nil) {
    builder_ = new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self);
  }
  return builder_;
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *)getParamsBean {
  if (paramsBean_ == nil) {
    paramsBean_ = new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self);
  }
  return paramsBean_;
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)getParamsBuilder {
  if (paramsBuilder_ == nil) {
    paramsBuilder_ = new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self);
  }
  return paramsBuilder_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 11, 12, -1, -1, -1, -1 },
    { NULL, "LADAbsoluteLayout_LayoutParams;", 0x2, 13, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 15, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 25, 26, -1, 27, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 29, 1, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(addWithASIWidget:withInt:);
  methods[11].selector = @selector(createLayoutParamsWithADView:);
  methods[12].selector = @selector(getLayoutParamsWithADView:);
  methods[13].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[14].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[15].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[16].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[17].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[18].selector = @selector(asNativeWidget);
  methods[19].selector = @selector(checkIosVersionWithNSString:);
  methods[20].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[21].selector = @selector(requestLayout);
  methods[22].selector = @selector(invalidate);
  methods[23].selector = @selector(setIdWithNSString:);
  methods[24].selector = @selector(getPluginWithNSString:);
  methods[25].selector = @selector(getBean);
  methods[26].selector = @selector(getBuilder);
  methods[27].selector = @selector(getParamsBean);
  methods[28].selector = @selector(getParamsBuilder);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 30, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 31, -1, -1 },
    { "absoluteLayout_", "LADAbsoluteLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "builder_", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "bean_", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBuilder_", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBean_", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "updateMeasuredDimension", "II", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setId", "getPlugin", &ComAsheraAbsolutelayoutAbsoluteLayoutImpl_LOCAL_NAME, &ComAsheraAbsolutelayoutAbsoluteLayoutImpl_GROUP_NAME, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt;LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean;LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;" };
  static const J2ObjcClassInfo _ComAsheraAbsolutelayoutAbsoluteLayoutImpl = { "AbsoluteLayoutImpl", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 29, 8, -1, 32, -1, -1, -1 };
  return &_ComAsheraAbsolutelayoutAbsoluteLayoutImpl;
}

@end

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl_GROUP_NAME, ComAsheraAbsolutelayoutAbsoluteLayoutImpl_LOCAL_NAME);
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init() {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, init)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init() {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, init)
}

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl_GROUP_NAME, localname);
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, initWithNSString_, localname)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, initWithNSString_, localname)
}

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_withNSString_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_setWidgetOnNativeClass(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_createLayoutParamsWithADView_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, ADView *view) {
  ADAbsoluteLayout_LayoutParams *layoutParams = (ADAbsoluteLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADAbsoluteLayout_LayoutParams class]);
  layoutParams = (ADAbsoluteLayout_LayoutParams *) cast_chk([view getLayoutParams], [ADAbsoluteLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ADAbsoluteLayout_LayoutParams_initWithInt_withInt_withInt_withInt_(-2, -2, 0, 0);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ADAbsoluteLayout_LayoutParams *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_getLayoutParamsWithADView_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, ADView *view) {
  return (ADAbsoluteLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADAbsoluteLayout_LayoutParams class]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAsheraAbsolutelayoutAbsoluteLayoutImpl)

@implementation ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$ {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)__javaClone:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 18, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(setMaxWidthWithInt:);
  methods[1].selector = @selector(setMaxHeightWithInt:);
  methods[2].selector = @selector(getMaxWidth);
  methods[3].selector = @selector(getMaxHeight);
  methods[4].selector = @selector(initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:);
  methods[5].selector = @selector(onMeasureWithInt:withInt:);
  methods[6].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[7].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[8].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[9].selector = @selector(newInstanceWithASIWidget:);
  methods[10].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[11].selector = @selector(getMethods);
  methods[12].selector = @selector(initialized);
  methods[13].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[14].selector = @selector(drawableStateChanged);
  methods[15].selector = @selector(offsetTopAndBottomWithInt:);
  methods[16].selector = @selector(offsetLeftAndRightWithInt:);
  methods[17].selector = @selector(setVisibilityWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "offsetTopAndBottom", "offsetLeftAndRight", "setVisibility" };
  static const J2ObjcClassInfo _ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt = { "AbsoluteLayoutExt", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 18, 5, 3, -1, -1, -1, -1 };
  return &_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt;
}

@end

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ADAbsoluteLayout_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt)

@implementation ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$ {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter {
  if (setter) {
    [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
  [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:);
  methods[1].selector = @selector(executeWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;", "execute", "Z", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandBuilder<Lcom/ashera/absolutelayout/AbsoluteLayoutImpl$AbsoluteLayoutCommandBuilder;>;" };
  static const J2ObjcClassInfo _ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder = { "AbsoluteLayoutCommandBuilder", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 2, 1, 0, -1, -1, 3, -1 };
  return &_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;
}

@end

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupCommandBuilder_init(self);
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder)

@implementation ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$ {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;" };
  static const J2ObjcClassInfo _ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean = { "AbsoluteLayoutBean", "com.ashera.absolutelayout", ptrTable, methods, NULL, 7, 0x1, 1, 0, 0, -1, -1, -1, -1 };
  return &_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean;
}

@end

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupBean_initWithASIWidget_(self, outer$);
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean)

@implementation ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$ {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (id)getLayoutXWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutX])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutX];
}

- (void)setLayoutXWithASIWidget:(id<ASIWidget>)w
                   withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutXWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutYWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutY])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutY];
}

- (void)setLayoutYWithASIWidget:(id<ASIWidget>)w
                   withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutYWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 5, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:);
  methods[1].selector = @selector(getLayoutXWithASIWidget:);
  methods[2].selector = @selector(setLayoutXWithASIWidget:withNSString:);
  methods[3].selector = @selector(getLayoutYWithASIWidget:);
  methods[4].selector = @selector(setLayoutYWithASIWidget:withNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;", "getLayoutX", "LASIWidget;", "setLayoutX", "LASIWidget;LNSString;", "getLayoutY", "setLayoutY" };
  static const J2ObjcClassInfo _ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean = { "AbsoluteLayoutParamsBean", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 5, 1, 0, -1, -1, -1, -1 };
  return &_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;
}

@end

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupParamsBean_init(self);
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean)

@implementation ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$ {
  ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutX {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_x"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutX {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_x"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutXWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_x"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutY {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_y"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutY {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_y"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutYWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_y"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, 3, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:);
  methods[1].selector = @selector(tryGetLayoutX);
  methods[2].selector = @selector(getLayoutX);
  methods[3].selector = @selector(setLayoutXWithNSString:);
  methods[4].selector = @selector(tryGetLayoutY);
  methods[5].selector = @selector(getLayoutY);
  methods[6].selector = @selector(setLayoutYWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComAsheraAbsolutelayoutAbsoluteLayoutImpl;", "setLayoutX", "LNSString;", "setLayoutY", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandParamsBuilder<Lcom/ashera/absolutelayout/AbsoluteLayoutImpl$AbsoluteLayoutCommandParamsBuilder;>;" };
  static const J2ObjcClassInfo _ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder = { "AbsoluteLayoutCommandParamsBuilder", "com.ashera.absolutelayout", ptrTable, methods, NULL, 7, 0x1, 7, 0, 0, -1, -1, 4, -1 };
  return &_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;
}

@end

void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupCommandParamsBuilder_init(self);
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder, initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder)
