//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutPlugin.java
//

#include "AbsoluteLayoutImpl.h"
#include "AbsoluteLayoutPlugin.h"
#include "J2ObjC_source.h"
#include "WidgetFactory.h"


@implementation ComAsheraAbsolutelayoutAbsoluteLayoutPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ComAsheraAbsolutelayoutAbsoluteLayoutPlugin = { "AbsoluteLayoutPlugin", "com.ashera.absolutelayout", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComAsheraAbsolutelayoutAbsoluteLayoutPlugin;
}

@end

void ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_init(ComAsheraAbsolutelayoutAbsoluteLayoutPlugin *self) {
  NSObject_init(self);
}

ComAsheraAbsolutelayoutAbsoluteLayoutPlugin *new_ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_init() {
  J2OBJC_NEW_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutPlugin, init)
}

ComAsheraAbsolutelayoutAbsoluteLayoutPlugin *create_ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_init() {
  J2OBJC_CREATE_IMPL(ComAsheraAbsolutelayoutAbsoluteLayoutPlugin, init)
}

void ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_initPlugin() {
  ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAsheraAbsolutelayoutAbsoluteLayoutPlugin)
