//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutPlugin.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "AbsoluteLayoutImpl.h"
#include "AbsoluteLayoutPlugin.h"
#include "J2ObjC_source.h"
#include "WidgetFactory.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@implementation ASAbsoluteLayoutPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASAbsoluteLayoutPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASAbsoluteLayoutPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASAbsoluteLayoutPlugin = { "AbsoluteLayoutPlugin", "com.ashera.absolutelayout", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASAbsoluteLayoutPlugin;
}

@end

void ASAbsoluteLayoutPlugin_init(ASAbsoluteLayoutPlugin *self) {
  NSObject_init(self);
}

ASAbsoluteLayoutPlugin *new_ASAbsoluteLayoutPlugin_init() {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutPlugin, init)
}

ASAbsoluteLayoutPlugin *create_ASAbsoluteLayoutPlugin_init() {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutPlugin, init)
}

void ASAbsoluteLayoutPlugin_initPlugin() {
  ASAbsoluteLayoutPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASAbsoluteLayoutImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAbsoluteLayoutPlugin)

J2OBJC_NAME_MAPPING(ASAbsoluteLayoutPlugin, "com.ashera.absolutelayout", "AS")
