//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\r\android\widget\AbsoluteLayout.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AbsoluteLayout")
#ifdef RESTRICT_AbsoluteLayout
#define INCLUDE_ALL_AbsoluteLayout 0
#else
#define INCLUDE_ALL_AbsoluteLayout 1
#endif
#undef RESTRICT_AbsoluteLayout

#if !defined (ADAbsoluteLayout_) && (INCLUDE_ALL_AbsoluteLayout || defined(INCLUDE_ADAbsoluteLayout))
#define ADAbsoluteLayout_

#define RESTRICT_ViewGroup 1
#define INCLUDE_ADViewGroup 1
#include "ViewGroup.h"

@class ADViewGroup_LayoutParams;
@class JavaLangBoolean;
@class JavaLangInteger;

@interface ADAbsoluteLayout : ADViewGroup

#pragma mark Public

- (instancetype)init;

#pragma mark Protected

- (bool)checkLayoutParamsWithADViewGroup_LayoutParams:(ADViewGroup_LayoutParams *)p;

- (ADViewGroup_LayoutParams *)generateDefaultLayoutParams;

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

@end

J2OBJC_EMPTY_STATIC_INIT(ADAbsoluteLayout)

FOUNDATION_EXPORT void ADAbsoluteLayout_init(ADAbsoluteLayout *self);

FOUNDATION_EXPORT ADAbsoluteLayout *new_ADAbsoluteLayout_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADAbsoluteLayout *create_ADAbsoluteLayout_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ADAbsoluteLayout)

@compatibility_alias RAndroidWidgetAbsoluteLayout ADAbsoluteLayout;


#endif

#if !defined (ADAbsoluteLayout_LayoutParams_) && (INCLUDE_ALL_AbsoluteLayout || defined(INCLUDE_ADAbsoluteLayout_LayoutParams))
#define ADAbsoluteLayout_LayoutParams_

#define RESTRICT_ViewGroup 1
#define INCLUDE_ADViewGroup_LayoutParams 1
#include "ViewGroup.h"

@class JavaLangInteger;

@interface ADAbsoluteLayout_LayoutParams : ADViewGroup_LayoutParams {
 @public
  int32_t x_;
  int32_t y_;
}

#pragma mark Public

- (instancetype)initWithInt:(int32_t)width
                    withInt:(int32_t)height
                    withInt:(int32_t)x
                    withInt:(int32_t)y;

- (instancetype)initWithADViewGroup_LayoutParams:(ADViewGroup_LayoutParams *)source;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithInt:(int32_t)arg0
                    withInt:(int32_t)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ADAbsoluteLayout_LayoutParams)

FOUNDATION_EXPORT void ADAbsoluteLayout_LayoutParams_initWithInt_withInt_withInt_withInt_(ADAbsoluteLayout_LayoutParams *self, int32_t width, int32_t height, int32_t x, int32_t y);

FOUNDATION_EXPORT ADAbsoluteLayout_LayoutParams *new_ADAbsoluteLayout_LayoutParams_initWithInt_withInt_withInt_withInt_(int32_t width, int32_t height, int32_t x, int32_t y) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADAbsoluteLayout_LayoutParams *create_ADAbsoluteLayout_LayoutParams_initWithInt_withInt_withInt_withInt_(int32_t width, int32_t height, int32_t x, int32_t y);

FOUNDATION_EXPORT void ADAbsoluteLayout_LayoutParams_initWithADViewGroup_LayoutParams_(ADAbsoluteLayout_LayoutParams *self, ADViewGroup_LayoutParams *source);

FOUNDATION_EXPORT ADAbsoluteLayout_LayoutParams *new_ADAbsoluteLayout_LayoutParams_initWithADViewGroup_LayoutParams_(ADViewGroup_LayoutParams *source) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADAbsoluteLayout_LayoutParams *create_ADAbsoluteLayout_LayoutParams_initWithADViewGroup_LayoutParams_(ADViewGroup_LayoutParams *source);

J2OBJC_TYPE_LITERAL_HEADER(ADAbsoluteLayout_LayoutParams)


#endif

#if !defined (ADAbsoluteLayout_AbsoulteLayout_) && (INCLUDE_ALL_AbsoluteLayout || defined(INCLUDE_ADAbsoluteLayout_AbsoulteLayout))
#define ADAbsoluteLayout_AbsoulteLayout_

@class ADAbsoluteLayout;

@interface ADAbsoluteLayout_AbsoulteLayout : NSObject

#pragma mark Package-Private

- (instancetype)initWithADAbsoluteLayout:(ADAbsoluteLayout *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ADAbsoluteLayout_AbsoulteLayout)

FOUNDATION_EXPORT void ADAbsoluteLayout_AbsoulteLayout_initWithADAbsoluteLayout_(ADAbsoluteLayout_AbsoulteLayout *self, ADAbsoluteLayout *outer$);

FOUNDATION_EXPORT ADAbsoluteLayout_AbsoulteLayout *new_ADAbsoluteLayout_AbsoulteLayout_initWithADAbsoluteLayout_(ADAbsoluteLayout *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ADAbsoluteLayout_AbsoulteLayout *create_ADAbsoluteLayout_AbsoulteLayout_initWithADAbsoluteLayout_(ADAbsoluteLayout *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ADAbsoluteLayout_AbsoulteLayout)


#endif

#pragma pop_macro("INCLUDE_ALL_AbsoluteLayout")
