//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AbsoluteLayoutPlugin")
#ifdef RESTRICT_AbsoluteLayoutPlugin
#define INCLUDE_ALL_AbsoluteLayoutPlugin 0
#else
#define INCLUDE_ALL_AbsoluteLayoutPlugin 1
#endif
#undef RESTRICT_AbsoluteLayoutPlugin

#if !defined (ASAbsoluteLayoutPlugin_) && (INCLUDE_ALL_AbsoluteLayoutPlugin || defined(INCLUDE_ASAbsoluteLayoutPlugin))
#define ASAbsoluteLayoutPlugin_

@interface ASAbsoluteLayoutPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAbsoluteLayoutPlugin)

FOUNDATION_EXPORT void ASAbsoluteLayoutPlugin_init(ASAbsoluteLayoutPlugin *self);

FOUNDATION_EXPORT ASAbsoluteLayoutPlugin *new_ASAbsoluteLayoutPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAbsoluteLayoutPlugin *create_ASAbsoluteLayoutPlugin_init(void);

FOUNDATION_EXPORT void ASAbsoluteLayoutPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASAbsoluteLayoutPlugin)

@compatibility_alias ComAsheraAbsolutelayoutAbsoluteLayoutPlugin ASAbsoluteLayoutPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_AbsoluteLayoutPlugin")
