//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutImpl.java
//

#include "AbsoluteLayout.h"
#include "AbsoluteLayoutImpl.h"
#include "BaseHasWidgets.h"
#include "HasWidgets.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "Rect.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"

@protocol JavaUtilMap;


#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ASAbsoluteLayoutImpl () {
 @public
  id uiView_;
  ADAbsoluteLayout *absoluteLayout_;
  ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *builder_;
  ASAbsoluteLayoutImpl_AbsoluteLayoutBean *bean_;
  ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *paramsBuilder_;
  ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *paramsBean_;
}

- (void)setWidgetOnNativeClass;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ADAbsoluteLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

@end

J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl, absoluteLayout_, ADAbsoluteLayout *)
J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl, builder_, ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)
J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl, bean_, ASAbsoluteLayoutImpl_AbsoluteLayoutBean *)
J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl, paramsBuilder_, ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)
J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl, paramsBean_, ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *)

__attribute__((unused)) static void ASAbsoluteLayoutImpl_setWidgetOnNativeClass(ASAbsoluteLayoutImpl *self);

__attribute__((unused)) static void ASAbsoluteLayoutImpl_createLayoutParamsWithADView_(ASAbsoluteLayoutImpl *self, ADView *view);

__attribute__((unused)) static ADAbsoluteLayout_LayoutParams *ASAbsoluteLayoutImpl_getLayoutParamsWithADView_(ASAbsoluteLayoutImpl *self, ADView *view);

@interface ASAbsoluteLayoutImpl_AbsoluteLayoutExt () {
 @public
  __unsafe_unretained ASAbsoluteLayoutImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  jint mMaxWidth_;
  jint mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl_AbsoluteLayoutExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl_AbsoluteLayoutExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASAbsoluteLayoutImpl_AbsoluteLayoutExt, templates_, id<JavaUtilMap>)

@interface ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder () {
 @public
  ASAbsoluteLayoutImpl *this$0_;
}

@end

@interface ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean () {
 @public
  ASAbsoluteLayoutImpl *this$0_;
}

@end

NSString *ASAbsoluteLayoutImpl_LOCAL_NAME = @"AbsoluteLayout";
NSString *ASAbsoluteLayoutImpl_GROUP_NAME = @"AbsoluteLayout";

@implementation ASAbsoluteLayoutImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_x"])) withTypeWithNSString:@"dimension"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_y"])) withTypeWithNSString:@"dimension"])) forChild]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASAbsoluteLayoutImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASAbsoluteLayoutImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASAbsoluteLayoutImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASAbsoluteLayoutImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  absoluteLayout_ = new_ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASAbsoluteLayoutImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASAbsoluteLayoutImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return absoluteLayout_;
}

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w {
  jboolean remove = [super removeWithASIWidget:w];
  [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(w);
  return remove;
}

- (jboolean)removeWithInt:(jint)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  jboolean remove = [super removeWithInt:index];
  if (index + 1 <= [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) getChildCount]) {
    [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) removeViewAtWithInt:index];
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
  return remove;
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASAbsoluteLayoutImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) addViewWithADView:view];
    }
    else {
      [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASAbsoluteLayoutImpl_createLayoutParamsWithADView_(self, view);
}

- (ADAbsoluteLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASAbsoluteLayoutImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADAbsoluteLayout_LayoutParams *layoutParams = ASAbsoluteLayoutImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_x", @"layout_y" }, 4)) {
    case 0:
    ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 2:
    {
      ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->x_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    }
    break;
    case 3:
    {
      ((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->y_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    }
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADAbsoluteLayout_LayoutParams *layoutParams = ASAbsoluteLayoutImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_x", @"layout_y" }, 4)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->height_);
    case 2:
    {
      return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->x_);
    }
    case 3:
    {
      return JavaLangInteger_valueOfWithInt_(((ADAbsoluteLayout_LayoutParams *) nil_chk(layoutParams))->y_);
    }
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASAbsoluteLayoutImpl_AbsoluteLayoutExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADAbsoluteLayout *) nil_chk(absoluteLayout_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(jboolean)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (id)getPluginWithNSString:(NSString *)plugin {
  return [((id<ASIAttributable>) nil_chk(ASWidgetFactory_getAttributableWithNSString_(plugin))) newInstanceWithASIWidget:self];
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutBean *)getBean {
  if (bean_ == nil) {
    bean_ = new_ASAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithASAbsoluteLayoutImpl_(self);
  }
  return bean_;
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)getBuilder {
  if (builder_ == nil) {
    builder_ = new_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithASAbsoluteLayoutImpl_(self);
  }
  return builder_;
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *)getParamsBean {
  if (paramsBean_ == nil) {
    paramsBean_ = new_ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithASAbsoluteLayoutImpl_(self);
  }
  return paramsBean_;
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)getParamsBuilder {
  if (paramsBuilder_ == nil) {
    paramsBuilder_ = new_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithASAbsoluteLayoutImpl_(self);
  }
  return paramsBuilder_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 11, 12, -1, -1, -1, -1 },
    { NULL, "LADAbsoluteLayout_LayoutParams;", 0x2, 13, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 15, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 22, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 23, 24, -1, 25, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 27, 28, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 29, 1, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(addWithASIWidget:withInt:);
  methods[11].selector = @selector(createLayoutParamsWithADView:);
  methods[12].selector = @selector(getLayoutParamsWithADView:);
  methods[13].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[14].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[15].selector = @selector(getViewClass);
  methods[16].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[17].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[18].selector = @selector(asNativeWidget);
  methods[19].selector = @selector(checkIosVersionWithNSString:);
  methods[20].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[21].selector = @selector(requestLayout);
  methods[22].selector = @selector(invalidate);
  methods[23].selector = @selector(setIdWithNSString:);
  methods[24].selector = @selector(setVisibleWithBoolean:);
  methods[25].selector = @selector(getPluginWithNSString:);
  methods[26].selector = @selector(getBean);
  methods[27].selector = @selector(getBuilder);
  methods[28].selector = @selector(getParamsBean);
  methods[29].selector = @selector(getParamsBuilder);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 30, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 31, -1, -1 },
    { "absoluteLayout_", "LADAbsoluteLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "builder_", "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "bean_", "LASAbsoluteLayoutImpl_AbsoluteLayoutBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBuilder_", "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBean_", "LASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setId", "setVisible", "Z", "getPlugin", &ASAbsoluteLayoutImpl_LOCAL_NAME, &ASAbsoluteLayoutImpl_GROUP_NAME, "LASAbsoluteLayoutImpl_AbsoluteLayoutExt;LASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;LASAbsoluteLayoutImpl_AbsoluteLayoutBean;LASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;LASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;" };
  static const J2ObjcClassInfo _ASAbsoluteLayoutImpl = { "AbsoluteLayoutImpl", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 30, 8, -1, 32, -1, -1, -1 };
  return &_ASAbsoluteLayoutImpl;
}

@end

void ASAbsoluteLayoutImpl_init(ASAbsoluteLayoutImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASAbsoluteLayoutImpl_GROUP_NAME, ASAbsoluteLayoutImpl_LOCAL_NAME);
}

ASAbsoluteLayoutImpl *new_ASAbsoluteLayoutImpl_init() {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl, init)
}

ASAbsoluteLayoutImpl *create_ASAbsoluteLayoutImpl_init() {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl, init)
}

void ASAbsoluteLayoutImpl_initWithNSString_(ASAbsoluteLayoutImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASAbsoluteLayoutImpl_GROUP_NAME, localname);
}

ASAbsoluteLayoutImpl *new_ASAbsoluteLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl, initWithNSString_, localname)
}

ASAbsoluteLayoutImpl *create_ASAbsoluteLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl, initWithNSString_, localname)
}

void ASAbsoluteLayoutImpl_initWithNSString_withNSString_(ASAbsoluteLayoutImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ASAbsoluteLayoutImpl *new_ASAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

ASAbsoluteLayoutImpl *create_ASAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASAbsoluteLayoutImpl_setWidgetOnNativeClass(ASAbsoluteLayoutImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASAbsoluteLayoutImpl_createLayoutParamsWithADView_(ASAbsoluteLayoutImpl *self, ADView *view) {
  ADAbsoluteLayout_LayoutParams *layoutParams = (ADAbsoluteLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADAbsoluteLayout_LayoutParams class]);
  layoutParams = (ADAbsoluteLayout_LayoutParams *) cast_chk([view getLayoutParams], [ADAbsoluteLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ADAbsoluteLayout_LayoutParams_initWithInt_withInt_withInt_withInt_(-2, -2, 0, 0);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ADAbsoluteLayout_LayoutParams *ASAbsoluteLayoutImpl_getLayoutParamsWithADView_(ASAbsoluteLayoutImpl *self, ADView *view) {
  return (ADAbsoluteLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADAbsoluteLayout_LayoutParams class]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAbsoluteLayoutImpl)

@implementation ASAbsoluteLayoutImpl_AbsoluteLayoutExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASAbsoluteLayoutImpl:(ASAbsoluteLayoutImpl *)outer$ {
  ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:[this$0_ getParent]];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:true];
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)__javaClone:(ASAbsoluteLayoutImpl_AbsoluteLayoutExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASAbsoluteLayoutImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(state0);
  methods[26].selector = @selector(state1);
  methods[27].selector = @selector(state2);
  methods[28].selector = @selector(state3);
  methods[29].selector = @selector(state4);
  methods[30].selector = @selector(stateYes);
  methods[31].selector = @selector(stateNo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASAbsoluteLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 29, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASAbsoluteLayoutImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASAbsoluteLayoutImpl_AbsoluteLayoutExt = { "AbsoluteLayoutExt", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 32, 6, 3, -1, -1, -1, -1 };
  return &_ASAbsoluteLayoutImpl_AbsoluteLayoutExt;
}

@end

void ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl_AbsoluteLayoutExt *self, ASAbsoluteLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ADAbsoluteLayout_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASAbsoluteLayoutImpl_AbsoluteLayoutExt *new_ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutExt, initWithASAbsoluteLayoutImpl_, outer$)
}

ASAbsoluteLayoutImpl_AbsoluteLayoutExt *create_ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutExt, initWithASAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAbsoluteLayoutImpl_AbsoluteLayoutExt)

@implementation ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder

- (instancetype)initWithASAbsoluteLayoutImpl:(ASAbsoluteLayoutImpl *)outer$ {
  ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithASAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter {
  if (setter) {
    [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
  [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAbsoluteLayoutImpl:);
  methods[1].selector = @selector(executeWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASAbsoluteLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASAbsoluteLayoutImpl;", "execute", "Z", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandBuilder<Lcom/ashera/absolutelayout/AbsoluteLayoutImpl$AbsoluteLayoutCommandBuilder;>;" };
  static const J2ObjcClassInfo _ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder = { "AbsoluteLayoutCommandBuilder", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 2, 1, 0, -1, -1, 3, -1 };
  return &_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;
}

@end

void ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *self, ASAbsoluteLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupCommandBuilder_init(self);
}

ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *new_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder, initWithASAbsoluteLayoutImpl_, outer$)
}

ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *create_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder, initWithASAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder)

@implementation ASAbsoluteLayoutImpl_AbsoluteLayoutBean

- (instancetype)initWithASAbsoluteLayoutImpl:(ASAbsoluteLayoutImpl *)outer$ {
  ASAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithASAbsoluteLayoutImpl_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAbsoluteLayoutImpl:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASAbsoluteLayoutImpl;" };
  static const J2ObjcClassInfo _ASAbsoluteLayoutImpl_AbsoluteLayoutBean = { "AbsoluteLayoutBean", "com.ashera.absolutelayout", ptrTable, methods, NULL, 7, 0x1, 1, 0, 0, -1, -1, -1, -1 };
  return &_ASAbsoluteLayoutImpl_AbsoluteLayoutBean;
}

@end

void ASAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl_AbsoluteLayoutBean *self, ASAbsoluteLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupBean_initWithASIWidget_(self, outer$);
}

ASAbsoluteLayoutImpl_AbsoluteLayoutBean *new_ASAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutBean, initWithASAbsoluteLayoutImpl_, outer$)
}

ASAbsoluteLayoutImpl_AbsoluteLayoutBean *create_ASAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutBean, initWithASAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAbsoluteLayoutImpl_AbsoluteLayoutBean)

@implementation ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean

- (instancetype)initWithASAbsoluteLayoutImpl:(ASAbsoluteLayoutImpl *)outer$ {
  ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithASAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (id)getLayoutXWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutX])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutX];
}

- (void)setLayoutXWithASIWidget:(id<ASIWidget>)w
                   withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutXWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutYWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutY])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutY];
}

- (void)setLayoutYWithASIWidget:(id<ASIWidget>)w
                   withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([((ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutYWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 5, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAbsoluteLayoutImpl:);
  methods[1].selector = @selector(getLayoutXWithASIWidget:);
  methods[2].selector = @selector(setLayoutXWithASIWidget:withNSString:);
  methods[3].selector = @selector(getLayoutYWithASIWidget:);
  methods[4].selector = @selector(setLayoutYWithASIWidget:withNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASAbsoluteLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASAbsoluteLayoutImpl;", "getLayoutX", "LASIWidget;", "setLayoutX", "LASIWidget;LNSString;", "getLayoutY", "setLayoutY" };
  static const J2ObjcClassInfo _ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean = { "AbsoluteLayoutParamsBean", "com.ashera.absolutelayout", ptrTable, methods, fields, 7, 0x1, 5, 1, 0, -1, -1, -1, -1 };
  return &_ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;
}

@end

void ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *self, ASAbsoluteLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupParamsBean_init(self);
}

ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *new_ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean, initWithASAbsoluteLayoutImpl_, outer$)
}

ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *create_ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean, initWithASAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAbsoluteLayoutImpl_AbsoluteLayoutParamsBean)

@implementation ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder

- (instancetype)initWithASAbsoluteLayoutImpl:(ASAbsoluteLayoutImpl *)outer$ {
  ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithASAbsoluteLayoutImpl_(self, outer$);
  return self;
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutX {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_x"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutX {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_x"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutXWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_x"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutY {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_y"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutY {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_y"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutYWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_y"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;", 0x1, 3, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASAbsoluteLayoutImpl:);
  methods[1].selector = @selector(tryGetLayoutX);
  methods[2].selector = @selector(getLayoutX);
  methods[3].selector = @selector(setLayoutXWithNSString:);
  methods[4].selector = @selector(tryGetLayoutY);
  methods[5].selector = @selector(getLayoutY);
  methods[6].selector = @selector(setLayoutYWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASAbsoluteLayoutImpl;", "setLayoutX", "LNSString;", "setLayoutY", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandParamsBuilder<Lcom/ashera/absolutelayout/AbsoluteLayoutImpl$AbsoluteLayoutCommandParamsBuilder;>;" };
  static const J2ObjcClassInfo _ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder = { "AbsoluteLayoutCommandParamsBuilder", "com.ashera.absolutelayout", ptrTable, methods, NULL, 7, 0x1, 7, 0, 0, -1, -1, 4, -1 };
  return &_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;
}

@end

void ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *self, ASAbsoluteLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupCommandParamsBuilder_init(self);
}

ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *new_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder, initWithASAbsoluteLayoutImpl_, outer$)
}

ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *create_ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder, initWithASAbsoluteLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder)
