//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AbsoluteLayoutImpl")
#ifdef RESTRICT_AbsoluteLayoutImpl
#define INCLUDE_ALL_AbsoluteLayoutImpl 0
#else
#define INCLUDE_ALL_AbsoluteLayoutImpl 1
#endif
#undef RESTRICT_AbsoluteLayoutImpl

#if !defined (ASAbsoluteLayoutImpl_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ASAbsoluteLayoutImpl))
#define ASAbsoluteLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASAbsoluteLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAbsoluteLayoutImpl)

inline NSString *ASAbsoluteLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASAbsoluteLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASAbsoluteLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASAbsoluteLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASAbsoluteLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASAbsoluteLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASAbsoluteLayoutImpl_init(ASAbsoluteLayoutImpl *self);

FOUNDATION_EXPORT ASAbsoluteLayoutImpl *new_ASAbsoluteLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAbsoluteLayoutImpl *create_ASAbsoluteLayoutImpl_init(void);

FOUNDATION_EXPORT void ASAbsoluteLayoutImpl_initWithNSString_(ASAbsoluteLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASAbsoluteLayoutImpl *new_ASAbsoluteLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAbsoluteLayoutImpl *create_ASAbsoluteLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASAbsoluteLayoutImpl_initWithNSString_withNSString_(ASAbsoluteLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASAbsoluteLayoutImpl *new_ASAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAbsoluteLayoutImpl *create_ASAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASAbsoluteLayoutImpl)

@compatibility_alias ComAsheraAbsolutelayoutAbsoluteLayoutImpl ASAbsoluteLayoutImpl;


#endif

#if !defined (ASAbsoluteLayoutImpl_AbsoluteLayoutExt_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ASAbsoluteLayoutImpl_AbsoluteLayoutExt))
#define ASAbsoluteLayoutImpl_AbsoluteLayoutExt_

#define RESTRICT_AbsoluteLayout 1
#define INCLUDE_ADAbsoluteLayout 1
#include "AbsoluteLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASAbsoluteLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASAbsoluteLayoutImpl_AbsoluteLayoutExt : ADAbsoluteLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASAbsoluteLayoutImpl:(ASAbsoluteLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASAbsoluteLayoutImpl_AbsoluteLayoutExt)

FOUNDATION_EXPORT void ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl_AbsoluteLayoutExt *self, ASAbsoluteLayoutImpl *outer$);

FOUNDATION_EXPORT ASAbsoluteLayoutImpl_AbsoluteLayoutExt *new_ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASAbsoluteLayoutImpl_AbsoluteLayoutExt *create_ASAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithASAbsoluteLayoutImpl_(ASAbsoluteLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASAbsoluteLayoutImpl_AbsoluteLayoutExt)


#endif

#pragma pop_macro("INCLUDE_ALL_AbsoluteLayoutImpl")
