//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AbsoluteLayoutImpl")
#ifdef RESTRICT_AbsoluteLayoutImpl
#define INCLUDE_ALL_AbsoluteLayoutImpl 0
#else
#define INCLUDE_ALL_AbsoluteLayoutImpl 1
#endif
#undef RESTRICT_AbsoluteLayoutImpl

#if !defined (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ComAsheraAbsolutelayoutAbsoluteLayoutImpl))
#define ComAsheraAbsolutelayoutAbsoluteLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean;
@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder;
@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder;
@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *)getBean;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *)getParamsBean;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAbsolutelayoutAbsoluteLayoutImpl)

inline NSString *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComAsheraAbsolutelayoutAbsoluteLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComAsheraAbsolutelayoutAbsoluteLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_init(void);

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_withNSString_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl)

#endif

#if !defined (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt))
#define ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_

#define RESTRICT_AbsoluteLayout 1
#define INCLUDE_ADAbsoluteLayout 1
#include "AbsoluteLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ASWidgetAttribute;
@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt : ADAbsoluteLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt)

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutExt)

#endif

#if !defined (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder))
#define ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl;

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)addAllModelWithId:(id)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                                           withId:(id)arg1;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)addModelWithId:(id)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)invalidate;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)requestLayout;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)reset;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetAddStatesFromChildren;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetAlpha;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetBackground;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetBackgroundTint;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetBackgroundTintMode;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetClickable;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetClipChildren;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetClipToPadding;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetContentDescription;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetDuplicateParentState;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetEnabled;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetFocusable;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetForeground;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetForegroundGravity;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetForegroundTint;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetForegroundTintMode;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetId;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosAccessibilityHint;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosAccessibilityLabel;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosAccessibilityTraits;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosAccessibilityValue;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosAlpha;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosBackgroundColor;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosClipsToBounds;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosContentScaleFactor;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosIsFocused;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosIsHidden;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosIsOpaque;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosLargeContentImage;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosLargeContentTitle;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosRestorationIdentifier;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosTag;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosTintColor;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetKeepScreenOn;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetLayoutDirection;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetLayoutMode;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetLongClickable;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetMaxHeight;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetMaxWidth;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetMinHeight;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetMinWidth;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetModelIdPath;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetModelParam;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetModelPojoToUi;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetModelSyncEvents;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetModelUiToPojo;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetPaddingBottom;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetPaddingEnd;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetPaddingLeft;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetPaddingRight;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetPaddingStart;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetPaddingTop;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetRotation;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetRotationX;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetRotationY;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetScaleX;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetScaleY;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetSelected;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetTextAlignment;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetTextDirection;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetTransformPivotX;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetTransformPivotY;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetTranslationX;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetTranslationY;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetTranslationZ;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetValidateForm;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)tryGetVisibility;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                                 withId:(id)arg1;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder)

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandBuilder)

#endif

#if !defined (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean))
#define ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl;
@protocol ASIWidget;

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean)

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutBean)

#endif

#if !defined (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean))
#define ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl;
@protocol ASIWidget;

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$;

- (id)getLayoutXWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutYWithASIWidget:(id<ASIWidget>)w;

- (void)setLayoutXWithASIWidget:(id<ASIWidget>)w
                   withNSString:(NSString *)value;

- (void)setLayoutYWithASIWidget:(id<ASIWidget>)w
                   withNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean)

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutParamsBean)

#endif

#if !defined (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_) && (INCLUDE_ALL_AbsoluteLayoutImpl || defined(INCLUDE_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder))
#define ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ComAsheraAbsolutelayoutAbsoluteLayoutImpl;

@interface ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl:(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *)outer$;

- (id)getLayoutX;

- (id)getLayoutY;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)reset;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutXWithNSString:(NSString *)value;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)setLayoutYWithNSString:(NSString *)value;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutMarginTop;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutX;

- (ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *)tryGetLayoutY;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder)

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *self, ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *new_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder *create_ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder_initWithComAsheraAbsolutelayoutAbsoluteLayoutImpl_(ComAsheraAbsolutelayoutAbsoluteLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAbsolutelayoutAbsoluteLayoutImpl_AbsoluteLayoutCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_AbsoluteLayoutImpl")
