//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\github_ashera\AbsoluteLayout\ios\src\main\java\com\ashera\absolutelayout\AbsoluteLayoutPlugin.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AbsoluteLayoutPlugin")
#ifdef RESTRICT_AbsoluteLayoutPlugin
#define INCLUDE_ALL_AbsoluteLayoutPlugin 0
#else
#define INCLUDE_ALL_AbsoluteLayoutPlugin 1
#endif
#undef RESTRICT_AbsoluteLayoutPlugin

#if !defined (ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_) && (INCLUDE_ALL_AbsoluteLayoutPlugin || defined(INCLUDE_ComAsheraAbsolutelayoutAbsoluteLayoutPlugin))
#define ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_

@interface ComAsheraAbsolutelayoutAbsoluteLayoutPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAbsolutelayoutAbsoluteLayoutPlugin)

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_init(ComAsheraAbsolutelayoutAbsoluteLayoutPlugin *self);

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutPlugin *new_ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComAsheraAbsolutelayoutAbsoluteLayoutPlugin *create_ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_init(void);

FOUNDATION_EXPORT void ComAsheraAbsolutelayoutAbsoluteLayoutPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAbsolutelayoutAbsoluteLayoutPlugin)

#endif

#pragma pop_macro("INCLUDE_ALL_AbsoluteLayoutPlugin")
